[package]
name = "abm_framework"
version = "0.1.0"
edition = "2021"

[lib]
name = "abm_framework"
crate-type = ["rlib", "cdylib"]

[dependencies]
rayon = "1.7.0"

[dev-dependencies]
proptest = "1.9.0"
insta = { version = "1.44.3", features = ["json"] }
criterion = "0.8.1"

[features]
default = []
rollback = []
